### ISSUE TITLE
Line Snaps

### ISSUE THREAD

**Issue by MutualEffort** [spencerjpotts/Ark-FisherMan#1]
Is there a specific resolution I am supposed to put it in, or full screen?

**Comment by spencerjpotts** [comment]
Yeah dude sorry, I'm still putting info together for the github, its 
RESOLUTION: 1920x1080
WINDOW MODE: WindowedFullscreen
GRAPHICS QUALITY: MEDIUM

IF THATS NOT WORKING ONLY WAY IS DEFAULT SETTINGS Sorry
