### ISSUE TITLE
Does not work on 1600x900 Screens.

### ISSUE THREAD

**Issue by FryoKnight** [spencerjpotts/Ark-FisherMan#10]
Pretty much as the title states.
But the goodnews is I did figure out how to get it to workafter some minor tweaking.

I would have just sent you the altered code, but there is no messaging system in GitHud...
But if you want, I can upload it later so you can either add it later to the master so others will not have to do the same as me. ^-^
Or I can just credit you for the original code. Up to you.

**Comment by spencerjpotts** [comment]
Cheers for helping dude :) haven't been on ark for a couple of weeks :(, Pull request is your friend for this man, i'll have a look at the changes and push them to the master you can also add it to your github as well no stress. join discord if you have anything else to talk about or other projects in mind 👍 thanks @FryoKnight

**Comment by FryoKnight** [comment]
Not really familiar with how to do anything on this site to be honest. ^-^"
I am just going to upload to my GitHub for now until something farther can be established...

**Comment by spencerjpotts** [comment]
Never heard anything from you.. :)
