### ISSUE TITLE
Stopped working

### ISSUE THREAD

**Issue by Freezier134a** [spencerjpotts/Ark-FisherMan#12]
worked for a few days then stopped. myself and friend both get pole snapping immediately once a fish is on , anyone else having this issue ?

**Comment by spencerjpotts** [comment]
are you using 1366x768? thanks for telling me 👍 , becaouse 1366x768 has known issues I'm going to have to fix really soon

**Comment by Freezier134a** [comment]
Sorry , no 1920x1080 ,worked like a charm for me, my buddy had to finally goto windowed full screen to get his to work , then 3 days later it quit on us both .

**Comment by Freezier134a** [comment]
It’s working again , I think it was because I didn’t have the gamma set to default , all good again !

**Comment by spencerjpotts** [comment]
haha okeydokie enjoy man
