### ISSUE TITLE
line snaps sometimes

### ISSUE THREAD

**Issue by santosho81** [spencerjpotts/Ark-FisherMan#15]
sometimes it works, sometimes it doesn't, but the majority of the time it snaps when its almost catching. the computer is a bit slow so is there any chace you can slow down a bit?

**Comment by spencerjpotts** [comment]
Hey man, sorry to hear about that, you can set the speed down by following these steps, it's pretty simple. Open the script "Ark-FisherMan-1920x1080.ahk" with notepad > change the speed variable on line 18 . i've created a link incase it's a bit daunting [Line 18 speed variable](https://github.com/spencerjpotts/Ark-FisherMan/blob/da9eae7a3568173a6eb35680fc4c4b1e7ef48f0b/Ark-FisherMan-1920x1080.ahk#L18) the speed is represented in milliseconds FYI

**Comment by spencerjpotts** [comment]
message back if that doesn't work it could be settings issue like gamma, resolution etc.... ty

**Comment by santosho81** [comment]
hey thanks for the reply works a lot better with 300 ms, but is slower chance of getting good loot too. there is still a problem with sun reflections on metal etc, witch causes the script to stop at some time ingame. 
I'm launching the game with low dx10 settings, have ingame settings to medium, FullscreenMode=1, UIScaling=1.000000 (i have a monitor/tv with edges missing so it stays at that scale)
also don't use gamma command. This is my second computer so its a bit low end, the script works fine on my main one.

**Comment by spencerjpotts** [comment]
Ok thanks for letting me know, i'll take some notes and see how I can come up with solutions for "low-budget" computer systems. if you have other question and need a quickish reply join the [discord channel](https://discord.gg/262RFta)
