### ISSUE TITLE
False positive on D

### ISSUE THREAD

**Issue by powerbard** [spencerjpotts/Ark-FisherMan#16]
For some reason, the letter D causes a false positive for another letter and snaps the line. Verified .ini settings, resolution, gamma. It reads the D and then decides the D was something else and snaps the line with the wrong letter. Any ideas or help? i am not familiar enough with the pixel mapping

**Comment by spencerjpotts** [comment]
Join the discord and tell me what steps you have taken plus config you have running etcc... or post them here :)

**Comment by powerbard** [comment]
Sent to discord. No steps taken yet, as the issue seems to be the cross check of “if D then check for C” but I am not versed in pixel mapping.

**Comment by powerbard** [comment]
Found the issue I believe, closing this ticket with the only thing changed. The windows UI scaling in resolution screen was set at “recommended 120%” forced it back to 100% and the D works as intended now.
