### ISSUE TITLE
Brazilian Portuguese Localization

### ISSUE THREAD

**Issue by LuisBlock23** [spencerjpotts/Ark-FisherMan#17]
**Good morning**. I loved your script and felt that it could be better and reach more people if my language was supported. That's why I modified your script to support it. Although everything seems to be going well, I keep testing to be sure. **Contact me to send the code**.

**Comment by spencerjpotts** [comment]
Join the discord and mention it

**Comment by LuisBlock23** [comment]
Ok, i'm in.

**Comment by spencerjpotts** [comment]
I'll do some stuff tomorrow. It's late in Australia right now mate. Cheers
for the help.

**Comment by LuisBlock23** [comment]
Ohh, ok. I will send the code in your personal discord. Good Night.
