### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by paperrain** [spencerjpotts/Ark-FisherMan#2]
Does not scan the letter, just pressing the letters randomly.

azqwxdazqwxdazqwxdazqwxdazqwxdazqwxd

**Comment by spencerjpotts** [comment]
It scans the letter, and presses the correct one, Have you got Default settings?

**Comment by paperrain** [comment]
Yes, i setup like this:

RESOLUTION: 1920x1080
WINDOW MODE: WindowedFullscreen
GRAPHICS QUALITY: MEDIUM

**Comment by spencerjpotts** [comment]
Reset to default settings please? I'm still working on my github page so info is shitty atm

**Comment by paperrain** [comment]
Np, you are god 👍 

Work only 1 time... :(

**Comment by spencerjpotts** [comment]
give me 30 minutes ill get it working for you :)

**Comment by spencerjpotts** [comment]
Have you followed the config file instructions? or any of the new ones? get back to me

**Comment by paperrain** [comment]
ill test!

**Comment by paperrain** [comment]
Doesn't work :( First 3 letters pressed perfectly but next fail. And only work sometimes (only 3-4 first letters).

**Comment by paperrain** [comment]
Does the language affect? because my game is on spanish language

**Comment by paperrain** [comment]
Fixed, game need to be in english. Add to info! Works perfectly!

**Comment by spencerjpotts** [comment]
lol! yep haven't even started on other languages yet man! cheers for letting me know, ill get on to that next
