### ISSUE TITLE
links in readme

### ISSUE THREAD

**Issue by ndaman** [spencerjpotts/Ark-FisherMan#3]
Not a big deal, but I noticed the links in the readme don't work, I think there is a ) in the url by mistake.

Thanks for sharing and documenting your script!

**Comment by spencerjpotts** [comment]
Yeep, making new readme as we type :), thanks dude, script working for you though haha?

**Comment by spencerjpotts** [comment]
fixed now :) thanks

**Comment by ndaman** [comment]
Thanks! Script works great, btw, very clever approach!
