### ISSUE TITLE
script dont work for me

### ISSUE THREAD

**Issue by Nackenschelle** [spencerjpotts/Ark-FisherMan#5]
iam running the latest ark update
and i followed the instructions in your github page but it wont press buttons on catch
any solution?

**Comment by spencerjpotts** [comment]
Hey there, I just logged in and the script was running fine for myself, what installation process did follow? Hit me up, I will get it working for you. :)

**Comment by Nackenschelle** [comment]
Game Language is English
Resolution is 1920x1080 WindowedFullscreen

in the beginning i tried the tutorial from: Game Configuration
after this i tried to use the reset function to use ark normal settings.
also wont work for me :/

**Comment by spencerjpotts** [comment]
Did you try the config file approach ?

**Comment by Nackenschelle** [comment]
yes more than a few times :/
