### ISSUE TITLE
hello scipt isnt working for me

### ISSUE THREAD

**Issue by MindaugasUlskis** [spencerjpotts/Ark-FisherMan#7]
here are my settings https://prnt.sc/gaj4xu

**Comment by Nackenschelle** [comment]
script works on max settings for me

did you press F5 after throw in fishing rod?

**Comment by MindaugasUlskis** [comment]
yes I did, can the problem be that I am using 2 monitors, but the game is on my main one?

**Comment by Nackenschelle** [comment]
i use 4 monitors. game runs on my main.
script works perfectly

**Comment by MindaugasUlskis** [comment]
what if my game is on other hdd then steam

is it a problem?

**Comment by Nackenschelle** [comment]
no thats not the problem.
my gamefiles are on a hdd too

did you use the latest version?

**Comment by MindaugasUlskis** [comment]
ye I think so
v265.0

**Comment by Nackenschelle** [comment]
latest version of the script

**Comment by MindaugasUlskis** [comment]
i downloaded it yday

**Comment by spencerjpotts** [comment]
@minde1123 is it running now?

**Comment by MindaugasUlskis** [comment]
Yes, had to reistall auto hotkey program, sry for not closing
